- http://blog.greptilian.com
- http://wiki.greptilian.com/about/pdurbin
- https://github.com/pdurbin
- http://twitter.com/philipdurbin
- http://www.iq.harvard.edu/people/philip-durbin
- http://linkedin.com/in/pdurbin
- http://sourcefu.com/members/pdurbin
- http://stackoverflow.com/users/19464/philip-durbin
- http://stackexchange.com/users/10330/philip-durbin?tab=accounts
- http://crimsonfu.github.com/members/pdurbin
- https://discourse.opensourcediversity.org/u/pdurbin
- https://discourse.opensourcedesign.net/u/pdurbin
- https://ask.cyberinfrastructure.org/u/pdurbin
- http://blogs.perl.org/users/philip_durbin/
- http://commandlinefu.com/commands/by/pdurbin
- http://huffduffer.com/philipdurbin
- http://soundcloud.com/philipdurbin
- http://en.wikipedia.org/wiki/user:pdurbin
