- http://wiki.greptilian.com
- https://github.com/pdurbin
- http://twitter.com/philipdurbin
- http://www.iq.harvard.edu/people/philip-durbin
- http://sourcefu.com/members/pdurbin
- https://plus.google.com/+PhilipDurbin
- http://stackoverflow.com/users/19464/philip-durbin
- http://unix.stackexchange.com/users/7494/philip-durbin
- http://serverfault.com/users/1156/philip-durbin
- http://stackexchange.com/users/10330/philip-durbin?tab=accounts
- http://blogs.perl.org/users/philip_durbin
- http://crimsonfu.github.com/members/pdurbin
- http://commandlinefu.com/commands/by/pdurbin
- http://linkedin.com/in/pdurbin
- http://huffduffer.com/philipdurbin
- http://soundcloud.com/philipdurbin
- http://en.wikipedia.org/wiki/user:pdurbin
- http://pluss.es/107770072576338242009/
