- http://github.com/pdurbin
- http://twitter.com/philipdurbin
- http://plus.google.com/107770072576338242009
- http://crimsonfu.github.com/members/pdurbin
- http://stackoverflow.com/users/19464/philip-durbin
- http://unix.stackexchange.com/users/7494/philip-durbin
- http://serverfault.com/users/1156/philip-durbin
- http://stackexchange.com/users/10330/philip-durbin?tab=accounts
- http://blogs.perl.org/users/philip_durbin
- http://commandlinefu.com/commands/by/pdurbin
- http://linkedin.com/in/pdurbin
- http://huffduffer.com/philipdurbin
- http://en.wikipedia.org/wiki/user:pdurbin
- http://builditwith.me/user/pdurbin  
- http://people.fas.harvard.edu/~pdurbin/blog
- http://pluss.es/107770072576338242009/
