- http://blog.greptilian.com
- http://wiki.greptilian.com/about/pdurbin
- https://bostonopen.dev/people/pdurbin
- https://github.com/pdurbin
- https://iq.harvard.edu/people/philip-durbin
- https://linkedin.com/in/pdurbin
- https://twitter.com/philipdurbin
- https://stackoverflow.com/users/19464/philip-durbin
- https://stackexchange.com/users/10330/philip-durbin?tab=accounts
- https://discourse.opensourcediversity.org/u/pdurbin
- https://discourse.opensourcedesign.net/u/pdurbin
- https://ask.cyberinfrastructure.org/u/pdurbin
- https://sourcefu.github.io/members/pdurbin
- https://crimsonfu.github.io/members/pdurbin
- https://blogs.perl.org/users/philip_durbin/
- https://commandlinefu.com/commands/by/pdurbin
- https://huffduffer.com/philipdurbin
- https://soundcloud.com/philipdurbin
- https://en.wikipedia.org/wiki/user:pdurbin
